---
# notify: 
#     - Mesos default config file
#     - Mesos master script
#     - Mesos slave script
#

- name: Mesos default config file
  template: src=templates/mesos.j2 dest=/etc/default/mesos

- name: Mesos master script
  template: src=templates/mesos-master.j2 dest=/etc/init/mesos-master.conf
  when: install_mode == 'master'
  when: install_mode == 'local'
  notify:
    - restart mesos-master

- name: Mesos slave script
  template: src=templates/mesos-slave.j2 dest=/etc/init/mesos-slave.conf
  when: install_mode == 'slave'
  when: install_mode == 'local'
  notify:
    - restart mesos-slave