---
- hosts: all
  sudo: True
  tasks:
    group_by: key={{ ansible_distribution }}
  roles:
    - common

- hosts: Ubuntu
  gather_facts: no
  sudo: True
  vars:
    platform_url_name: "ubuntu"
    package_type: "deb"
    version: "0.15.0"
    file_name: "mesos_{{version}}_{{facter_architecture}}.{{package_type}}"
    base_url: "http://downloads.mesosphere.io/master"
    download_url: "{{base_url}}/{{platform_url_name}}/{{ansible_distribution_version}}/{{file_name}}"
    dest_file: "/tmp/{{file_name}}"
  roles:
    - ubuntu
    - deploy