---
- hosts: all
  sudo: True
  # vars_files: # does not work
    # - vars/default.yml
  tasks:
    - include_vars: vars/default.yml
    - action: group_by key={{ ansible_distribution }}
  roles:
    - common

- hosts: Ubuntu
  gather_facts: no
  sudo: True
  vars:
    platform_url_name: "ubuntu"
    package_type: "deb"
  roles:
    - ubuntu
    - deploy
