---
- hosts: all
  sudo: True
  tasks:
    group_by: key={{ ansible_distribution }}
  roles:
    - common

- hosts: Ubuntu
  gather_facts: no
  sudo: True
  vars:
    platform_url_name: "ubuntu"
    version: "0.14.2"
    file_name: "mesos_{{version}}_{{facter_architecture}}.deb"
    base_url: "http://downloads.mesosphere.io/master"
    download_url: "{{base_url}}/{{ansible_distribution}}/{{ansible_distribution_version}}/{{file_name}}"
  roles:
    - ubuntu
    - deploy