---
- debug: msg="Install Mode is {{mesos_install_mode}}"

- name: Delete master script
  file: path=/etc/default/mesos.conf state=absent

- name: Mesos default config file
  template: src=mesos.j2 dest=/etc/default/mesos

- name: create work dir
  file: path=/var/mesos state=directory
