---
- name: Install os packages
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
    - wget
    - curl
    - g++
    - gcc
    - python-setuptools
    - python-dev
    - python-protobuf
    - python-dev
    - python-pip
    - libcurl4-openssl-dev
    - libsasl2-2
    - libsasl2-dev
    - libcurl3
    - unzip

- name: Install zookeeper packages
  apt: pkg={{item}} state=present 
  with_items:
    - zookeeperd
  when: mesos_install_mode == "master" or mesos_install_mode == "master-slave"

- name: Install Debian Docker
  shell: curl -sSL https://get.docker.io/ubuntu/ | sudo sh
  sudo: yes

- name: Install Mesos Debian Package
  shell: DEBIAN_FRONTEND=noninteractive dpkg -i --force-confnew {{mesos_dest_file}} 
  sudo: yes
