---
- name: Install zookeeper packages
  apt: pkg={{item}} state=present 
  with_items:
    - zookeeperd

- name: Create zookeeper config file
  template: src=zoo.cfg.j2 dest=/etc/zookeeper/conf/zoo.cfg

- name: Create zookeeper myid file
  template: src=zoo_id.j2 dest=/etc/zookeeper/conf/myid

- name: Restart zookeeper
  shell: start zookeeper || restart zookeeper 
  sudo: yes
