---
- name: Install os packages
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
    - wget
    - curl
    - g++
    - gcc
    - python-setuptools
    - python-dev
    - python-protobuf
    - python-dev
    - libcurl4-openssl-dev
    - libsasl2-2
    - libsasl2-dev
    - libcurl3
    - unzip

- name: Install master os packages
  apt: pkg={{item}} state=present 
  with_items:
    - zookeeperd
  when: mesos_install_mode == "master" or mesos_install_mode == "master-slave"

- name: Download mesos {{mesos_version}} deb package
  get_url: url={{mesos_download_url}} dest={{mesos_dest_file}}

- name: Install Mesos Debian Package
  shell: DEBIAN_FRONTENT=noninteractive dpkg -i --force-confnew {{mesos_dest_file}} 
  sudo: yes
