---
# Here I am force loading default since ansible processes includes
# first, then implicitly loads default.
- include_vars: "{{ ansible_os_family }}.yml"

- include: common.yml

# Here we are using the debian package if debian
- include: Debian.yml
  when: ansible_os_family == "Debian"

- include: slave.yml
  when: mesos_install_mode == "slave" or mesos_install_mode == "master-slave"

- include: deploy.yml
