---
# Here we are using the debian package if debian
- include_vars: "{{ ansible_os_family }}.yml"

- include: common.yml

# Here we are using the debian package if debian
- include: Debian.yml
  when: ansible_os_family == "Debian"

- include: zookeeper.yml
  when: mesos_install_mode == "master" or mesos_install_mode == "master-slave"

- include: mesos.yml
