---
- name: Add Cloudera Repo for Zookeeper
  get_url: url=http://archive.cloudera.com/cdh4/redhat/6/x86_64/cdh/cloudera-cdh4.repo dest=/etc/yum.repos.d/ owner=root group=root mode=0644

- name: Remove Zookeeper Directory
  file: state=absent path=/var/lib/zookeeper/

- name: Install zookeeper packages
  yum: name={{item}} state=present 
  with_items:
    - libselinux-python 
    - zookeeper-server

- name: Init zookeeper
  shell: zookeeper-server-initialize
  sudo: yes

- name: Create zookeeper config file
  template: src=zoo.cfg.j2 dest=/etc/zookeeper/conf/zoo.cfg

- name: Create Zookeeper Directory
  file: state=directory path=/var/lib/zookeeper/ owner=zookeeper group=zookeeper

- name: Create zookeeper myid file
  template: src=zoo_id.j2 dest=/var/lib/zookeeper/myid

- name: Restart zookeeper
  shell: service zookeeper-server restart
  sudo: yes
