---
- name: Add mesosphere repo
  yum: name=http://repos.mesosphere.io/el/6/noarch/RPMS/mesosphere-el-repo-6-2.noarch.rpm state=present

- include: RedHat_zookeeper.yml
  when: mesos_install_mode == "master" or mesos_install_mode == "master-slave"

- name: Install os packages
  yum: name={{item}} state=present
  with_items:
    - wget
    - curl
    - unzip
    - libselinux-python 
    - python-setuptools
    - mesos-{{mesos_version}}

- name: Install Docker
  yum: pkg=docker-io state=present
