---
- name: Overwrite hostname config
  template: src=hostname.j2 dest=/etc/mesos-slave/hostname

- name: Turn on slave checkpoint
  shell: touch /etc/mesos-slave/checkpoint
  when: mesos_slave_checkpoint == "yes"

- name: Support Docker containerizers
  shell: echo 'docker,mesos' > /etc/mesos-slave/containerizers
  when: docker_support == "yes"
