---
- name: Install os packages
  apt: pkg={{item}} state=present
  with_items: 
    - wget
    - curl 
    - g++ 
    - gcc 
    - zookeeper-bin 
    - zookeeperd 
    - python-setuptools 
    - python-dev 
    - libcurl4-openssl-dev 
    - libsasl2-2 
    - libsasl2-dev 
    - libcurl3 
    - openjdk-{{java_version}}-jre-headless
    - openjdk-{{java_version}}-jdk

- name: Resolve {{libjvm_path}}
  shell: find {{libjvm_path}}
  register: libjvm_path_resolved

# Here we get back to ansible land...
- name: Check for {{libjvm_path_resolved}}
  stat: path={{libjvm_path_resolved.stdout}}
  register: libjvm

- name: Link libjvm
  shell: ln -nsf {{libjvm_path_resolved.stdout}} {{libjvm_symlink_path}}
  when: libjvm.stat.exists == true

- name: Check if symlink created
  stat: path={{libjvm_symlink_path}}
  register: libjvm_symlink

- fail: msg="Could not create libjvm symlink {{libjvm_symlink_path}}"
  when: libjvm_symlink.stat.exists == False
